#公共配置
server:
  #端口号
  port: 80
  context-path: /

spring:
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  application:
    name: coupon-service
  redis:
    host: 192.168.171.127
    port: 6379
    password: redis
    timeout: 10000ms
    jedis:
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000ms # 连接池中的最小空闲连接

  #数据源
  datasource:
    url: jdbc:mysql://192.168.171.127:3306/county_life?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: root
    #    password: y2iaciej
    password: root
    # mysql驱动
    driverClassName: com.mysql.cj.jdbc.Driver
    # oracle驱动
    # driverClassName: oracle.jdbc.driver.OracleDriver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

#mybatis
mybatis:
  type-aliases-package: com.ddup.county.life.entity
  mapper-locations: classpath:mapper/**/*.xml
  mapUnderscoreToCamelCase: true
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql
